// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1f3Ib9hIvYvI-oVJTSjuls9iXBpvvP-A',
    appId: '1:252498272942:web:e0e9673e248821b3edc33f',
    messagingSenderId: '252498272942',
    projectId: 'ngajile-app',
    authDomain: 'ngajile-app.firebaseapp.com',
    storageBucket: 'ngajile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCB0YFwxY2CyFD8j0kn2uPceCh1JBOdc',
    appId: '1:252498272942:android:3d527b6cab6271d7edc33f',
    messagingSenderId: '252498272942',
    projectId: 'ngajile-app',
    storageBucket: 'ngajile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5oxMwpkd6ztFz48wail9chUcw3nrR1OY',
    appId: '1:252498272942:ios:fc9727963130f436edc33f',
    messagingSenderId: '252498272942',
    projectId: 'ngajile-app',
    storageBucket: 'ngajile-app.firebasestorage.app',
    iosBundleId: 'com.example.sm6aplikasiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5oxMwpkd6ztFz48wail9chUcw3nrR1OY',
    appId: '1:252498272942:ios:fc9727963130f436edc33f',
    messagingSenderId: '252498272942',
    projectId: 'ngajile-app',
    storageBucket: 'ngajile-app.firebasestorage.app',
    iosBundleId: 'com.example.sm6aplikasiku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1f3Ib9hIvYvI-oVJTSjuls9iXBpvvP-A',
    appId: '1:252498272942:web:e971a294ac1bd2deedc33f',
    messagingSenderId: '252498272942',
    projectId: 'ngajile-app',
    authDomain: 'ngajile-app.firebaseapp.com',
    storageBucket: 'ngajile-app.firebasestorage.app',
  );
}
